# Enable Docker Provider.
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
# Required
endpoint = "unix:///var/run/docker.sock"

# Default base domain used for the frontend rules.
# Required
domain = "docker.localhost"
